name: Android Build

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest # Use a Linux environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Use Temurin OpenJDK
          java-version: '17' # Use JDK 17, which is compatible with Gradle 8.4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk